# Generated by Django 5.1.2 on 2024-11-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(db_index=True, max_length=17)),
                ('created_at', models.DateTimeField()),
                ('firmware_version', models.CharField(max_length=10)),
                ('log', models.TextField()),
            ],
        ),
    ]
